name: Keep Supabase Alive

on:
  schedule:
    - cron: '0 */12 * * *'  # Every 12 hours
  workflow_dispatch:        # Optional: manual run

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Curl Supabase Health Endpoint
        run: curl -s https://faodhpwvhonpyxlughls.supabase.co/auth/v1/health
